[package]
name = "prime_finder"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
crossbeam = "0.8.4"
chrono = "0.4.38"
csv = "1.3.0"
